
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

# Local Configuration (DO NOT UPLOAD THIS FILE)
azure.client.id=PASTE_YOUR_REAL_CLIENT_ID_HERE
azure.authority=https://login.microsoftonline.com/common/
azure.scope=https://outlook.office.com/IMAP.AccessAsUser.All
