package com.mycompany.emailtracker.ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.mycompany.emailtracker.core.EmailConfig;
import com.mycompany.emailtracker.core.EmailMessage;
import com.mycompany.emailtracker.core.EmailService;
import com.mycompany.emailtracker.core.EmailServiceImplemented;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;
import java.util.List;
/**
 *
 * @author aaron
 */
public class MainWindow extends javax.swing.JFrame {
    
    // Add this ONE line here:
    private EmailService emailService;
    private List<EmailMessage> currentEmails;
    private javax.swing.table.TableRowSorter<DefaultTableModel> rowSorter;

    public MainWindow() {
        initComponents(); // LEAVE THIS LINE ALONE!
        
        // Add these 3 lines right under initComponents():
        EmailConfig config = new EmailConfig(null, ""); 
        emailService = new EmailServiceImplemented(config);
        setupTable();
        setupSearch();
    }
    
    private void setupTable() {
        String[] columns = {"Sender", "Subject", "Date"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        tblEmails.setModel(model);

        rowSorter = new javax.swing.table.TableRowSorter<>(model);
        tblEmails.setRowSorter(rowSorter);

        // The Click Listener
        tblEmails.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting() && tblEmails.getSelectedRow() != -1) {
                
                // Get the row clicked on the screen
                int viewIndex = tblEmails.getSelectedRow();
                
                // Translate screen row to actual data row
                int modelIndex = tblEmails.convertRowIndexToModel(viewIndex);
                
                if (currentEmails != null && modelIndex < currentEmails.size()) {
                    EmailMessage clickedEmail = currentEmails.get(modelIndex);
                    String bodyText = clickedEmail.getContent();
                    
                    if (bodyText != null && bodyText.toLowerCase().contains("<html")) {
                        txtEmailBody.setContentType("text/html");
                    } else {
                        txtEmailBody.setContentType("text/plain");
                    }
                    
                    txtEmailBody.setEditable(false);
                    txtEmailBody.setText(bodyText);
                    txtEmailBody.setCaretPosition(0); 
                }
            }
        });
        }
    
    private void setupSearch() {
        // This listens to every keystroke in the text field
        txtSearch.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filterTable(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filterTable(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filterTable(); }
        });
    }

    // The actual filtering logic
    private void filterTable() {
        String text = txtSearch.getText();
        if (text.trim().length() == 0) {
            rowSorter.setRowFilter(null); // Show everything if box is empty
        } else {
            // (?i) makes the search case-insensitive!
            rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        btnFetch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmails = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtEmailBody = new javax.swing.JEditorPane();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFetch.setText("Fetch Emails");
        btnFetch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchActionPerformed(evt);
            }
        });

        tblEmails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEmails);

        jScrollPane4.setViewportView(txtEmailBody);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnFetch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFetch)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchActionPerformed
        new Thread(() -> {
            try {
                emailService.connect();
                
                // UPDATE THIS LINE: Save the result to our class variable
                currentEmails = emailService.fetchEmails();

                SwingUtilities.invokeLater(() -> {
                    DefaultTableModel model = (DefaultTableModel) tblEmails.getModel();
                    model.setRowCount(0); 
                    
                    // UPDATE THIS LINE: Loop through currentEmails
                    for (EmailMessage email : currentEmails) {
                        Object[] rowData = {
                            email.getSender(), 
                            email.getSubject(), 
                            email.getReceivedDate()
                        };
                        model.addRow(rowData);
                    }
                });
                
            } catch (Exception e) {
                e.printStackTrace();
            }finally {
                // --- 4. RESTORE UI STATE ---
                // The 'finally' block ALWAYS runs, whether the try succeeds or fails.
                SwingUtilities.invokeLater(() -> {
                    btnFetch.setEnabled(true);
                    btnFetch.setText("Fetch Emails"); // Make sure this matches your original button text
                    setCursor(java.awt.Cursor.getDefaultCursor());
                });
            }
        }).start();
    }//GEN-LAST:event_btnFetchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFetch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblEmails;
    private javax.swing.JEditorPane txtEmailBody;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
